from gm_shield.core.config import settings

# Ollama Connection
OLLAMA_HOST = settings.OLLAMA_BASE_URL

# Model Aliases
MODEL_QUERY = settings.OLLAMA_MODEL_GENERAL
MODEL_SHEET = settings.OLLAMA_MODEL_GENERAL  # Same model for now
MODEL_REFERENCE_FAST = settings.OLLAMA_MODEL_GENERAL
MODEL_REFERENCE_SMART = settings.OLLAMA_MODEL_STRUCTURED
MODEL_ENCOUNTER = settings.OLLAMA_MODEL_CREATIVE
MODEL_TAGGING = settings.OLLAMA_MODEL_GENERAL

# Configuration
TIMEOUT_DEFAULT = 30.0
TIMEOUT_GENERATION = 60.0
MAX_RETRIES = 3
